const {
  NODE_ENV,
  PORT,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  COOKIE_SECRET,
  ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_LIFE,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GCP_PROJECT_ID,
  GCP_STORAGE_BUCKET_ID,
  GCP_SERVICE_ACCOUNT_KEY,
} = process.env;

module.exports = {
  NODE_ENV,
  PORT,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  COOKIE_SECRET,
  ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_LIFE,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GCP_PROJECT_ID,
  GCP_STORAGE_BUCKET_ID,
  GCP_SERVICE_ACCOUNT_KEY,
};
